rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'prefectures/:prefecture_id/cities/:city_id', to: 'cities#index', as: 'cities'
  resources :reviews
  get 'offices/:ieul_office_id', to: 'offices#index', as: 'offices'

  resources :assessment_requests, only: %i[index create] do
    resources :thanks, only: %i[index]
  end
  get 'assessment_requests/done', to: 'assessment_requests#done'
  resources :thanks
  mount KomachiHeartbeat::Engine => '/ops'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

rails/app/views/shared/_company_card.html.erb
<% if office.reviews.order(release_date: :desc).first %>
    <div class="border my-4 p-3 rounded-3">
        <%= link_to offices_path(office.id), class: "a-company" do %>
            <div class="row my-3">
                <div class="col-lg-2">
                    <div><%= office.company.name %></div>
                    <div>★
                        <%= office.reviews.order(release_date: :desc).first.contract_price_satisfaction %>
                    </div>
                </div>
                <div class="col">
                    <div>営業時間：<%= office.business_time %></div>
                    <div>定休日：<%= office.regular_holiday %></div>
                    <div>住所：<%= office.address %></div>
                </div>
            </div>
            <div class="row my-3">
                <div class="col-lg-2">
                    <div>会社の決め手:</div>
                </div>
                <div class="col">
                    <%= office.reviews.order(release_date: :desc).first.reason_for_choosing_office %>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

rails/app/views/shared/_review_card.html.erb
<% @reviews.each do |review| %>
    <div class="border my-3">
        <%= link_to reviews_path(id: review.id), class: "a-company" do %>
            <div><strong><%=  review.headline %>：★<%= review.contract_price_satisfaction %></strong></div>
            <div><%= review.reason_for_support_satiosfaction %></div>
            <div class=" offset-lg-7">
                成約価格 <%= number_format(review.contract_price)%>（<%= review.city.name %>・<%= review.sale_date%>に売却）
            </div>
        <% end %>
    </div>
<% end %>