rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'prefectures/:prefecture_id/cities/:city_id', to: 'cities#index', as: 'cities'
  resources :reviews
  get 'offices/:ieul_office_id', to: 'offices#index', as: 'offices'

  resources :assessment_requests, only: %i[index create] do
    resources :thanks, only: %i[index]
  end
  get 'assessment_requests/done', to: 'assessment_requests#done'
  resources :thanks
  mount KomachiHeartbeat::Engine => '/ops'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

rails/app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  belongs_to :prefecture
  has_many :offices, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :assessable_areas, dependent: :destroy
  has_many :assessable_offices, through: :assessable_areas, source: :office, dependent: :destroy
end

rails/app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def index
    @offices = Office.includes(:reviews).includes(:assessable_cities)
                     .where(assessable_cities: { id: params[:city_id] }).all.page(params[:page]).per(5)
    Rails.logger.debug params[:city_id]
    Rails.logger.debug @offices
    @city = City.find(params[:city_id])
    @cities_without_target_city = @city.prefecture.cities.reject { |city| city == @city }
  end
end

rails/app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

rails/app/views/cities/index.html.erb
<% content_for :title, "エリアページ" %>
<% content_for :description, "指定したエリアに存在する不動産会社の情報を見ることができます" %>
<% content_for :is_noindex, @offices.blank? %>
<% breadcrumb :root %>

<h1 class="text-center"><%= @city.prefecture.name %><%= @city.name %>の不動産会社</h1>
<% @offices.each do |office| %>
  <%= render 'shared/company_card', office: office %>
<% end %>

<%= paginate @offices, theme: 'bootstrap-5'%>

<div class="container mt-3 mb-3 border border-2 border-gray rounded-3 ">
  <div>
    <p class="border-bottom border-dark mt-3", style="font-weight: bold;"><%= @city.prefecture.name%>全域</p>
  </div>
  <div class="row">
<% @cities_without_target_city.each do |city| %>
      <div class="col-md-2 mb-1">
        <%=link_to city.name, cities_path(@city.prefecture.id, city.id)  %> </div>
<% end %>
  </div>
</div>